### ISSUE TITLE
Improved Interface Requirements from Milestone 1

### ISSUE THREAD

**Issue by gabbsv1** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#248]

**Comment by gabbsv1** [comment]
Done

**Comment by lex939** [comment]
Duplicate issue 

@Cruiz102: will mark as not fixed for now, you can choose what to do with this issue by Milestone 2 end
